server:
  port: 8080

spring:
  autoconfigure:
    #db연결 x
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  swagger-ui:
    #접속 url: http://localhost:8080/swagger-ui/index.html
    enabled: true


